alias ..='cd ..'
alias Desktop='cd ~/Desktop'
alias Downloads='cd ~/Downloads'
alias a-remove='sudo apt remove'
alias base='/home/hamza/PROJECTS/clang/base.c/base'
alias bashlang='cd /home/hamza/PROJECTS/bash/'
alias battery='acpi | awk '\''NR==2 {gsub(",", "");print $4}'\'''
alias c='clear'
alias clang='cd ~/PROJECTS/clang'
alias cpu='ps auxf | sort -nr -k 3 | head -5'
alias disk='df -h | grep zbengued'
alias download='yt-dlp -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'
alias egrep='egrep --color=auto'
alias exa='exa --icons=always'
alias fgrep='fgrep --color=auto'
alias gccw='gcc -Wall -Wextra -Werror'
alias grep='grep --color=auto'
alias h='history'
alias install='sudo apt install'
alias ip='ifconfig | grep -w inet | awk '\''NR == 2 {print $2}'\'''
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias lowercase='lowercaseText'
alias ls='ls --color=auto'
alias m='main'
alias n='nano *.js'
alias nd='node *.js'
alias o='cd ~/linux-commands && sudo nano learn'
alias of='cd ~/linux-commands/'
alias open='xdg-open'
alias own='/home/hamza/scripts/make'
alias purge='sudo apt purge'
alias remove='sudo apt remove'
alias s='sudo'
alias s-remove='sudo snap remove'
alias screenshots='cd /home/hamza/Pictures/Screenshots/'
alias search='sudo apt search'
alias ser='python3 -m http.server 8000'
alias server='python3 -m http.server'
alias sinstall='sudo snap install'
alias sourcebash='source ~/.bashrc'
alias spurge='sudo snap remove --purge'
alias sremove='sudo snap remove --remove'
alias ss='sudo systemctl status'
alias ssearch='sudo snap search'
alias t='touch'
alias tor='cd ~/.local/share/applications/ && env ./start-tor-browser.desktop && cd -'
alias update='sudo apt update'
alias upgrade='sudo apt upgrade'
alias uppercase='uppercaseText'
alias v='vim'
alias vimbash='vim ~/.bashrc'
alias x='exit'
alias valias='vim ~/.alias.sh'
alias sbash='source ~/.bashrc'
alias vbash='vim ~/.bashrc'
alias f='source ~/file.sh'
alias md='mkdir'
alias rf='rm -rf'
alias slist='snap list'
alias list='apt list'
alias q='exit'
alias autoremove='sudo apt autoremove && sudo apt autopurge && sudo apt autoclean'
alias run='watch -d -n 0.1'
alias q=exit
alias sshk='TERM=xterm ssh -o sendEnv=TERM'
alias normer='python3 -m c_formatter_42 -c'
alias lock='pkill ft_lock && ft_lock'
