# ==========================================
# B O O T S T R A P   A U T O M A T I Q U E
# ==========================================

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins/'

if-shell "test ! -d ~/.local/share/tmux/plugins/tpm" \
   "run-shell 'git clone https://github.com/tmux-plugins/tpm ~/.local/share/tmux/plugins/tpm'"

# ==========================================
# C H A R G E M E N T   D E S   M O D U L E S
# ==========================================

source-file ~/.config/tmux/conf/general.conf
source-file ~/.config/tmux/conf/mapping.conf
source-file ~/.config/tmux/conf/plugins.conf

# ==========================================
# A U T O - I N S T A L L   P L U G I N S
# ==========================================

run-shell '~/.local/share/tmux/plugins/tpm/bin/install_plugins'
